"""Abstract base class for all clip scorers.

Agent Notes:
- All scorers must inherit from ClipScorer
- Scorers receive CandidateClip and return ScoredClip
- Use profile + intent to select the right scorer class
- ClipScorerRegistry handles polymorphic scorer dispatch
- Scorers should be composable via score fusion in ScoringService
- Never mutate input candidates; return new ScoredClip instances
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from vaclip.models.media import ClipIntent, ContentProfile


@dataclass
class CandidateClip:
    """A candidate clip window for scoring.

    Generated by segmentation stage from transcript segments.
    Contains timing, transcript text, and raw feature signals.
    """

    run_id: str
    candidate_id: str
    start: float          # seconds
    end: float            # seconds
    text: str             # transcript text for this window
    segment_ids: list[int] = field(default_factory=list)
    features: dict[str, Any] = field(default_factory=dict)

    @property
    def duration(self) -> float:
        """Clip duration in seconds."""
        return self.end - self.start

    @property
    def word_count(self) -> int:
        """Word count from transcript text."""
        return len(self.text.split())


@dataclass
class ScoredClip:
    """A scored clip with ranking information.

    Output contract from scoring stage.
    Consumed by export stage to select and cut final clips.
    """

    candidate: CandidateClip
    score: float                            # 0.0 - 1.0 composite score
    scorer_name: str
    profile: ContentProfile
    intent: ClipIntent
    score_breakdown: dict[str, float] = field(default_factory=dict)
    reasoning: str = ""                     # human-readable explanation

    @property
    def start(self) -> float:
        """Clip start time in seconds."""
        return self.candidate.start

    @property
    def end(self) -> float:
        """Clip end time in seconds."""
        return self.candidate.end

    @property
    def duration(self) -> float:
        """Clip duration in seconds."""
        return self.candidate.duration


class ClipScorer(ABC):
    """Abstract base class for all VAClip clip scorers.

    Subclasses implement profile/intent-specific scoring logic.
    Examples:
    - PodcastFunnyScorer
    - PodcastInsightfulScorer
    - GamingHypeScorer
    - GenericHighlightScorer
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique scorer identifier."""
        ...

    @property
    @abstractmethod
    def supported_profiles(self) -> list[ContentProfile]:
        """List of content profiles this scorer is optimized for."""
        ...

    @property
    @abstractmethod
    def supported_intents(self) -> list[ClipIntent]:
        """List of clip intents this scorer targets."""
        ...

    @abstractmethod
    def score(self, candidate: CandidateClip) -> ScoredClip:
        """Score a candidate clip and return a ScoredClip.

        Implementations must:
        1. Extract relevant features from candidate.features and candidate.text
        2. Compute a normalized score between 0.0 and 1.0
        3. Populate score_breakdown with individual signal scores
        4. Populate reasoning with a brief human-readable explanation
        5. Never mutate the input candidate

        Args:
            candidate: The CandidateClip to score.

        Returns:
            ScoredClip with score and breakdown populated.
        """
        ...

    def supports(self, profile: ContentProfile, intent: ClipIntent) -> bool:
        """Return True if this scorer handles the given profile+intent combo.

        Used for polymorphic scorer selection.
        Subclasses can override for more precise matching.
        """
        return (
            profile in self.supported_profiles
            and intent in self.supported_intents
        )
